In [ ]:
# Modules: a file containing python definations, functions and statements

#Packages: a way of collecting related modules to gather within a single tree like hierarchy.
#eg Numpy, SciPy, Pandas have hundreds of modules within them

# Steps :
"""
1) Find Package
    where to find package? Github # search for package, go to terminal in your computer,
    press command t to open new terminal, type: conda install packagename OR
                                                pip install packagename
    
2) install package
3)import package # import numpy ( for whole package)
                   from numpy import functionname ( for importing just function)
OR
4)import functions within a package

"""


---

#Numpy and Arrays
difference between list and array
list: can have different data type, while slicing list it creats copy of list so change will only happen on that copy
array: can only have one data type, if you have different data type it will convert all data type into one type
      while slicing array it will not creat copy of list instead make change into original list. to creat a copy type
      list.presstab
      array also have inbuilt functions to find mean, std


In [2]:
list1 = [1,2,3,4,5,6] 
import numpy as np
a = np.array(list1)
print(a)

[1 2 3 4 5 6]


In [3]:
list1[2:]

[3, 4, 5, 6]

In [5]:
l2 = list1[2:4]
print(l2)

[3, 4]


In [12]:
list1.copy # press tab after . to see all the functions

<built-in method copy of list object at 0x114cc6408>


In [10]:
#Functions in matrics
# a[2,3] gives 2nd row and 3rd column
# a[0,:] gives 1st row all column
# a[:,3] gives 3rd column all row

In [15]:
import numpy as np # creating new array
mydata = np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [26]:
a = np.reshape(mydata,(5,4))# reshaping array
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [29]:
print(a[2,3])
print(a[2,:])
print(a[:,3])



11
[ 8  9 10 11]
[ 3  7 11 15 19]


In [31]:
a = np.reshape(mydata,(5,4), order="C")
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [32]:
a = np.reshape(mydata,(5,4), order="F")
print(a)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [36]:
#OOP concept
# instead of doing 
#np.reshape(mydata,(5,4)
#We can directly do 
mydata.reshape((5,4))   #reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
import numpy as np
list1 = np.arange(0,20)
matrix1 = np.reshape(list1,(5,4))
print(matrix1)
print(matrix1[2,2]) # print number 10 from matrix 1



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
10


In [12]:
#OOP concept: we can use reshape function directly into our data because list1 was created using np.arange 
list1.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
#np.array function
list1 = [1,2,3,4,]
list2 = ['ram','shyam','hari','gopal']
list3 = [90,60,70,80]
array1 = np.array([list1,list2,list3])
print(array1)

[['1' '2' '3' '4']
 ['ram' 'shyam' 'hari' 'gopal']
 ['90' '60' '70' '80']]
